### ISSUE TITLE
The module net.bajawa.pager does not support the ABI: x86

### ISSUE THREAD

**Issue by arifje** [mudderman/ViewPager-Module-Demo#11]
[WARN] :   The module net.bajawa.pager does not support the ABI: x86
[WARN] :   It only supports the following ABIs: armeabi, armeabi-v7a
[WARN] :   Your application will most likely encounter issues

Can't build with SDK 3.5.1.GA

**Comment by mudderman** [comment]
Use this version: http://tomas.hau.so/static/files/so.hau.tomas.pager-android-1.0.zip

See: http://tomas.hau.so/posts/2013/10/02/viewpager-module-revisited/
