### ISSUE TITLE
No x86 support in module

### ISSUE THREAD

**Issue by timanrebel** [mudderman/ViewPager-Module-Demo#3]
Could you recompile the net.bajawa.pager module and add X86 support? At the moment I can't test my app on Genymotion anymore, only on device

Thanks!

**Comment by mudderman** [comment]
The version available on the Appcelerator Marketplace is not the most current one. See this:
http://tomas.hau.so/posts/2013/10/02/viewpager-module-revisited/

**Comment by timanrebel** [comment]
Thanks! I was not aware of that. The new module is working on x86. I can't however get the tabs to show. That might have something to do with the type integer. Could you give me a hint on which is which? It is not mentioned in your blogpost.

**Comment by timanrebel** [comment]
I set it to 1 and it works. (What are the other options? :))

**Comment by mudderman** [comment]
Yeah, I've been a bit sloppy in announcing the reworked version. :)

The tab options are:

TABS_NONE = 0
TABS_NORMAL = 1
TABS_SCROLLING = 2
TABS_MARKET = 3

And the option defaults to TABS_NONE (as you noticed)

**Comment by timanrebel** [comment]
No problem! Already glad that there is a x86 version :) And what are the options for the indicator?

**Comment by mudderman** [comment]
INDICATOR_NONE (10)
INDICATOR_LINE (11)
