### ISSUE TITLE
Soft Keyboard showing on create

### ISSUE THREAD

**Issue by kenrickvaz** [mudderman/ViewPager-Module-Demo#4]
On creating the page viewer, the soft keyboard shows. I am using the pageCreated event from the latest version (http://tomas.hau.so/posts/2013/10/02/viewpager-module-revisited/). Is there some way to avoid the keyboard from showing. I am on Titanium Appcelerator 3.2.1, Android v4.4.2

**Comment by mudderman** [comment]
Are you using some other view in the ViewPager that might cause the keyboard to show? I haven't heard about this problem from anyone else.

**Comment by kenrickvaz** [comment]
Sorry for the trouble. It was an issue with appcelerator and not with the module. Apologies! :)

**Comment by mudderman** [comment]
:thumbsup:
