### ISSUE TITLE
Scroll to TAB ?

### ISSUE THREAD

**Issue by ankesh27** [mudderman/ViewPager-Module-Demo#7]
Hello, Is there an event wherein I can Scroll the tab to a desired Index ?

Cheers!
Ankesh

**Comment by ankesh27** [comment]
Here is the Solution I found.

tabs.addEventListener(TabsModule.PAGE_SELECTED_EVENT_NAME, function(e) {
//Current Tab Position
i = e.position;
var allViews = arguments[0].source.views;
//Current View
activeView = allViews[i].view;
});

**Comment by jpriebe** [comment]
Ankesh -- can you clarify?  Are you trying to programmatically set the current tab?  Or are you trying to listen to an event that is fired when the _user_ scrolls to a new tab?

I don't understand your example code.  There's already a pageChange event you can use to listen for page changes.  I'm not sure what this PAGE_SELECTED_EVENT_NAME event is, or what you're doing when you set activeView.

If you have figured out a way to programmatically change the current tab, I would be very interested in understanding it!

**Comment by ankesh27** [comment]
@jpriebe can you please let me know what exactly you want so that I can help you on this..

**Comment by ankesh27** [comment]
```
var TabsModule = require('com.navid.tabs');
var tabs = TabsModule.createPagerTabs({
    current : 1,
    top : 40,
    tab : {
        backgroundColor : "#efefef",
        alignment : TabsModule.ALIGNMENT_LEFT,
        indicatorColor : "#7f7d7e",
        color : "#000000",
        underlineColor : "#7f7d7e",
        font : {
            size : (12),
            color : "#ffffff",
            colorSelected : "#ffffff",
            bold : false
        },
        padding : 30,
        dividerPadding : 5
    },
    views : [{
        title : "Home ",
        view : homeView
    },{
        title : "Tab 1 ",
        view : tab1view
    }, {
        title : "Tab2 ",
        view : tab2view
    }, {
        title : "Tab 3 ",
        view : tab3view
    }]
});
```

```
tabs.select(2); //where 2 is the tab index you want to select. You can call this in any eventlistner like button click ...
```

Let me if this is not what you want.

**Comment by mudderman** [comment]
That's not my ViewPager module you're using ;)

**Comment by ankesh27** [comment]
LMAO ;) Sorry. Wrong post wrong page. :) But the important part is that things should work.

sorry again :)
