### ISSUE TITLE
method to programmatically change current page

### ISSUE THREAD

**Issue by jpriebe** [mudderman/ViewPager-Module-Demo#8]
(nice module -- thanks for sharing this)

Is there an undocumented method to programmatically set the current page?  I don't see one, and if I try to set the currentPage property directly, nothing happens.

**Comment by mudderman** [comment]
Yep.

``` javascript
scrollTo(pageNumber, scroll);
```

where `scroll` is an optional boolean which determines if the tab should scroll into view or just display. iirc it defaults to true.

there are also two convenience methods:

``` javascript
nextPage(scroll);
previousPage(scroll);
```

you can also use `initialPage: (integer)` in the creation of the viewpager to set the "starting page" of the pager.

**Comment by jpriebe** [comment]
Perfect -- thanks!
