### ISSUE TITLE
can't suppress indicator?

### ISSUE THREAD

**Issue by jpriebe** [mudderman/ViewPager-Module-Demo#9]
I've tried to suppress the indicator style both by setting indicator.style to PagerModule.NONE and by setting the indicator.height to 0.

But I always get the thick line indicator under the selected tab label.

**Comment by mudderman** [comment]
The indicator settings control the bottom indicator, i.e. not the line under the tabs.
You should be able to control the indicator under the tabs by manipulating the `lineHeight`, `lineHeightSelected`, `lineColor`, and `lineColorSelected` properties

**Comment by jpriebe** [comment]
OK -- I see those now.  Sorry.

Word of warning: don't try to use shorthand hex codes (e.g. "#000") for colors; it will crash.  Use 6-digit hex codes instead (e.g. "#000000")
